// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/four_fingerprint.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FourFingerprintBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FourFingerprintBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FourFingerprintBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// 1. Scale / DPI calibration
  int fp_calibrate_scale(
    ffi.Pointer<ffi.Uint8> rgb_frame,
    int width,
    int height,
    ffi.Pointer<ffi.Float> hand_landmarks,
    int landmark_count,
    ffi.Pointer<ffi.Int32> finger_codes,
    int num_fingers,
    ffi.Pointer<ffi.Float> out_scale_factor,
  ) {
    return _fp_calibrate_scale(
      rgb_frame,
      width,
      height,
      hand_landmarks,
      landmark_count,
      finger_codes,
      num_fingers,
      out_scale_factor,
    );
  }

  late final _fp_calibrate_scalePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('fp_calibrate_scale');
  late final _fp_calibrate_scale = _fp_calibrate_scalePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.Int32>,
          int,
          ffi.Pointer<ffi.Float>,
        )
      >();

  /// 2. Finger segmentation mask
  int fp_segment_fingers(
    ffi.Pointer<ffi.Uint8> grayscale_img,
    int width,
    int height,
    ffi.Pointer<ffi.Float> hand_landmarks,
    int landmark_count,
    ffi.Pointer<ffi.Uint8> out_mask,
    ffi.Pointer<FpBoundingBox> out_boxes,
    int max_fingers,
    ffi.Pointer<ffi.Int32> out_num_fingers,
  ) {
    return _fp_segment_fingers(
      grayscale_img,
      width,
      height,
      hand_landmarks,
      landmark_count,
      out_mask,
      out_boxes,
      max_fingers,
      out_num_fingers,
    );
  }

  late final _fp_segment_fingersPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<FpBoundingBox>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_segment_fingers');
  late final _fp_segment_fingers = _fp_segment_fingersPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<FpBoundingBox>,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 3. Illumination normalization + specular highlight removal
  int fp_normalize_illumination(
    ffi.Pointer<ffi.Uint8> input_img,
    int width,
    int height,
    ffi.Pointer<ffi.Uint8> output_img,
  ) {
    return _fp_normalize_illumination(input_img, width, height, output_img);
  }

  late final _fp_normalize_illuminationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
          )
        >
      >('fp_normalize_illumination');
  late final _fp_normalize_illumination = _fp_normalize_illuminationPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<ffi.Uint8>)
      >();

  /// 4. Cylindrical surface unwarping
  int fp_unwarp_cylindrical(
    ffi.Pointer<ffi.Uint8> input_img,
    int width,
    int height,
    ffi.Pointer<FpBoundingBox> finger_roi,
    double finger_width_mm,
    double finger_length_mm,
    ffi.Pointer<ffi.Uint8> output_img,
    int out_width,
    int out_height,
    ffi.Pointer<ffi.Float> out_scale_factor,
  ) {
    return _fp_unwarp_cylindrical(
      input_img,
      width,
      height,
      finger_roi,
      finger_width_mm,
      finger_length_mm,
      output_img,
      out_width,
      out_height,
      out_scale_factor,
    );
  }

  late final _fp_unwarp_cylindricalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<FpBoundingBox>,
            ffi.Float,
            ffi.Float,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('fp_unwarp_cylindrical');
  late final _fp_unwarp_cylindrical = _fp_unwarp_cylindricalPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<FpBoundingBox>,
          double,
          double,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
        )
      >();

  /// 5. Liveness / anti-spoofing gate
  int fp_check_liveness(
    ffi.Pointer<ffi.Uint8> grayscale_img,
    int width,
    int height,
    ffi.Pointer<ffi.Float> hand_landmarks,
    int landmark_count,
    ffi.Pointer<ffi.Int32> out_is_live,
  ) {
    return _fp_check_liveness(
      grayscale_img,
      width,
      height,
      hand_landmarks,
      landmark_count,
      out_is_live,
    );
  }

  late final _fp_check_livenessPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_check_liveness');
  late final _fp_check_liveness = _fp_check_livenessPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 6. NFIQ2 quality assessment
  int fp_init_nfiq2(ffi.Pointer<ffi.Char> model_dir) {
    return _fp_init_nfiq2(model_dir);
  }

  late final _fp_init_nfiq2Ptr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>)>>(
        'fp_init_nfiq2',
      );
  late final _fp_init_nfiq2 = _fp_init_nfiq2Ptr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int fp_assess_quality(
    ffi.Pointer<ffi.Uint8> grayscale_img,
    int width,
    int height,
    int ppi,
    int finger_code,
    ffi.Pointer<ffi.Int32> out_quality_score,
  ) {
    return _fp_assess_quality(
      grayscale_img,
      width,
      height,
      ppi,
      finger_code,
      out_quality_score,
    );
  }

  late final _fp_assess_qualityPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_assess_quality');
  late final _fp_assess_quality = _fp_assess_qualityPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 7. Minutiae extraction (MINDTCT)
  int fp_extract_minutiae(
    ffi.Pointer<ffi.Uint8> grayscale_img,
    int width,
    int height,
    int ppi,
    ffi.Pointer<FpMinutia> out_minutiae,
    int max_minutiae,
    ffi.Pointer<ffi.Int32> out_num_minutiae,
  ) {
    return _fp_extract_minutiae(
      grayscale_img,
      width,
      height,
      ppi,
      out_minutiae,
      max_minutiae,
      out_num_minutiae,
    );
  }

  late final _fp_extract_minutiaePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<FpMinutia>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_extract_minutiae');
  late final _fp_extract_minutiae = _fp_extract_minutiaePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          ffi.Pointer<FpMinutia>,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 8. Template matching (BOZORTH3)
  int fp_match_templates(
    ffi.Pointer<FpMinutia> probe,
    int probe_count,
    ffi.Pointer<FpMinutia> gallery,
    int gallery_count,
    ffi.Pointer<ffi.Int32> out_match_score,
  ) {
    return _fp_match_templates(
      probe,
      probe_count,
      gallery,
      gallery_count,
      out_match_score,
    );
  }

  late final _fp_match_templatesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<FpMinutia>,
            ffi.Int32,
            ffi.Pointer<FpMinutia>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_match_templates');
  late final _fp_match_templates = _fp_match_templatesPtr
      .asFunction<
        int Function(
          ffi.Pointer<FpMinutia>,
          int,
          ffi.Pointer<FpMinutia>,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 9. ISO/IEC 19794-2 template export
  int fp_export_iso_template(
    ffi.Pointer<FpMinutia> minutiae,
    int count,
    int finger_position,
    int ppi,
    ffi.Pointer<ffi.Uint8> out_buffer,
    int buffer_size,
    ffi.Pointer<ffi.Int32> out_length,
  ) {
    return _fp_export_iso_template(
      minutiae,
      count,
      finger_position,
      ppi,
      out_buffer,
      buffer_size,
      out_length,
    );
  }

  late final _fp_export_iso_templatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<FpMinutia>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_export_iso_template');
  late final _fp_export_iso_template = _fp_export_iso_templatePtr
      .asFunction<
        int Function(
          ffi.Pointer<FpMinutia>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 10. WSQ compression / decompression
  int fp_wsq_compress(
    ffi.Pointer<ffi.Uint8> grayscale_img,
    int width,
    int height,
    int ppi,
    ffi.Pointer<ffi.Uint8> out_buffer,
    int buffer_size,
    ffi.Pointer<ffi.Int32> out_length,
  ) {
    return _fp_wsq_compress(
      grayscale_img,
      width,
      height,
      ppi,
      out_buffer,
      buffer_size,
      out_length,
    );
  }

  late final _fp_wsq_compressPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_wsq_compress');
  late final _fp_wsq_compress = _fp_wsq_compressPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  int fp_wsq_decompress(
    ffi.Pointer<ffi.Uint8> wsq_data,
    int data_length,
    ffi.Pointer<ffi.Uint8> out_grayscale,
    int out_width,
    int out_height,
    ffi.Pointer<ffi.Int32> out_actual_width,
    ffi.Pointer<ffi.Int32> out_actual_height,
    ffi.Pointer<ffi.Int32> out_ppi,
  ) {
    return _fp_wsq_decompress(
      wsq_data,
      data_length,
      out_grayscale,
      out_width,
      out_height,
      out_actual_width,
      out_actual_height,
      out_ppi,
    );
  }

  late final _fp_wsq_decompressPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_wsq_decompress');
  late final _fp_wsq_decompress = _fp_wsq_decompressPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 11. Burst frame best-frame selection
  int fp_select_best_frame(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> frames,
    int frame_count,
    int width,
    int height,
    int ppi,
    ffi.Pointer<ffi.Int32> out_best_index,
  ) {
    return _fp_select_best_frame(
      frames,
      frame_count,
      width,
      height,
      ppi,
      out_best_index,
    );
  }

  late final _fp_select_best_framePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_select_best_frame');
  late final _fp_select_best_frame = _fp_select_best_framePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          int,
          int,
          int,
          int,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 12. Full pipeline: process a single slap frame
  int fp_process_slap_frame(
    ffi.Pointer<ffi.Uint8> rgb_frame,
    int width,
    int height,
    ffi.Pointer<ffi.Float> hand_landmarks,
    int landmark_count,
    ffi.Pointer<ffi.Int32> finger_codes,
    ffi.Pointer<FpSlapResult> out_result,
    ffi.Pointer<FpMinutia> out_minutia_buffer,
    int max_minutiae,
    ffi.Pointer<ffi.Uint8> out_image_buffer,
    int image_buffer_size,
  ) {
    return _fp_process_slap_frame(
      rgb_frame,
      width,
      height,
      hand_landmarks,
      landmark_count,
      finger_codes,
      out_result,
      out_minutia_buffer,
      max_minutiae,
      out_image_buffer,
      image_buffer_size,
    );
  }

  late final _fp_process_slap_framePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<FpSlapResult>,
            ffi.Pointer<FpMinutia>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('fp_process_slap_frame');
  late final _fp_process_slap_frame = _fp_process_slap_framePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<FpSlapResult>,
          ffi.Pointer<FpMinutia>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// 13. Capture state machine
  int fp_state_machine_init(ffi.Pointer<FpStateMachine> state) {
    return _fp_state_machine_init(state);
  }

  late final _fp_state_machine_initPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<FpStateMachine>)>
      >('fp_state_machine_init');
  late final _fp_state_machine_init = _fp_state_machine_initPtr
      .asFunction<int Function(ffi.Pointer<FpStateMachine>)>();

  int fp_state_machine_update(ffi.Pointer<FpStateMachine> state, int event) {
    return _fp_state_machine_update(state, event);
  }

  late final _fp_state_machine_updatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<FpStateMachine>, ffi.Int32)
        >
      >('fp_state_machine_update');
  late final _fp_state_machine_update = _fp_state_machine_updatePtr
      .asFunction<int Function(ffi.Pointer<FpStateMachine>, int)>();

  int fp_state_machine_get_step(ffi.Pointer<FpStateMachine> state) {
    return _fp_state_machine_get_step(state);
  }

  late final _fp_state_machine_get_stepPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<FpStateMachine>)>
      >('fp_state_machine_get_step');
  late final _fp_state_machine_get_step = _fp_state_machine_get_stepPtr
      .asFunction<int Function(ffi.Pointer<FpStateMachine>)>();

  /// 14. Encrypted storage (AES-256-GCM)
  int fp_encrypt_data(
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
    ffi.Pointer<ffi.Uint8> key,
    int key_len,
    ffi.Pointer<ffi.Uint8> out_encrypted,
    ffi.Pointer<ffi.Int32> out_enc_len,
  ) {
    return _fp_encrypt_data(
      data,
      data_len,
      key,
      key_len,
      out_encrypted,
      out_enc_len,
    );
  }

  late final _fp_encrypt_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_encrypt_data');
  late final _fp_encrypt_data = _fp_encrypt_dataPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  int fp_decrypt_data(
    ffi.Pointer<ffi.Uint8> data,
    int data_len,
    ffi.Pointer<ffi.Uint8> key,
    int key_len,
    ffi.Pointer<ffi.Uint8> out_decrypted,
    ffi.Pointer<ffi.Int32> out_dec_len,
  ) {
    return _fp_decrypt_data(
      data,
      data_len,
      key,
      key_len,
      out_decrypted,
      out_dec_len,
    );
  }

  late final _fp_decrypt_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('fp_decrypt_data');
  late final _fp_decrypt_data = _fp_decrypt_dataPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// 15. Process a single finger
  int fp_process_finger(
    ffi.Pointer<ffi.Uint8> rgb_frame,
    int width,
    int height,
    ffi.Pointer<ffi.Float> hand_landmarks,
    int landmark_count,
    int finger_code,
    ffi.Pointer<FpBoundingBox> finger_roi,
    double scale_factor,
    ffi.Pointer<FpProcessedFinger> out_finger,
  ) {
    return _fp_process_finger(
      rgb_frame,
      width,
      height,
      hand_landmarks,
      landmark_count,
      finger_code,
      finger_roi,
      scale_factor,
      out_finger,
    );
  }

  late final _fp_process_fingerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<FpBoundingBox>,
            ffi.Float,
            ffi.Pointer<FpProcessedFinger>,
          )
        >
      >('fp_process_finger');
  late final _fp_process_finger = _fp_process_fingerPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
          int,
          int,
          ffi.Pointer<FpBoundingBox>,
          double,
          ffi.Pointer<FpProcessedFinger>,
        )
      >();

  int fp_is_match(int match_score) {
    return _fp_is_match(match_score);
  }

  late final _fp_is_matchPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32)>>('fp_is_match');
  late final _fp_is_match = _fp_is_matchPtr.asFunction<int Function(int)>();

  /// 16. Memory management
  void fp_free_slap_result(ffi.Pointer<FpSlapResult> result) {
    return _fp_free_slap_result(result);
  }

  late final _fp_free_slap_resultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FpSlapResult>)>>(
        'fp_free_slap_result',
      );
  late final _fp_free_slap_result = _fp_free_slap_resultPtr
      .asFunction<void Function(ffi.Pointer<FpSlapResult>)>();

  void fp_free_processed_finger(ffi.Pointer<FpProcessedFinger> finger) {
    return _fp_free_processed_finger(finger);
  }

  late final _fp_free_processed_fingerPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FpProcessedFinger>)>
      >('fp_free_processed_finger');
  late final _fp_free_processed_finger = _fp_free_processed_fingerPtr
      .asFunction<void Function(ffi.Pointer<FpProcessedFinger>)>();

  /// 17. Version info
  ffi.Pointer<ffi.Char> fp_get_version() {
    return _fp_get_version();
  }

  late final _fp_get_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'fp_get_version',
      );
  late final _fp_get_version = _fp_get_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

/// Data structures
final class FpMinutia extends ffi.Struct {
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  /// degrees * 10
  @ffi.Int32()
  external int direction;

  /// 0=bifurcation, 1=ridge ending
  @ffi.Int32()
  external int type;

  /// 0.0 - 1.0
  @ffi.Double()
  external double reliability;
}

final class FpFingerResult extends ffi.Struct {
  @ffi.Int32()
  external int finger_code;

  @ffi.Int32()
  external int quality_score;

  @ffi.Int32()
  external int minutia_count;

  @ffi.Int32()
  external int is_live;

  @ffi.Int32()
  external int resolution_ppi;

  @ffi.Double()
  external double scale_factor;
}

final class FpSlapResult extends ffi.Struct {
  @ffi.Int32()
  external int success;

  @ffi.Int32()
  external int num_fingers;

  @ffi.Int32()
  external int total_minutiae;

  @ffi.Array.multi([10])
  external ffi.Array<FpFingerResult> fingers;

  external ffi.Pointer<FpMinutia> all_minutiae;

  @ffi.Int32()
  external int all_minutiae_count;

  external ffi.Pointer<ffi.Uint8> iso_template;

  @ffi.Int32()
  external int iso_template_length;
}

final class FpStateMachine extends ffi.Struct {
  @ffi.Int32()
  external int current_step;

  @ffi.Int32()
  external int left_ready;

  @ffi.Int32()
  external int right_ready;

  @ffi.Int32()
  external int thumbs_ready;

  @ffi.Int32()
  external int initialized;

  @ffi.Int32()
  external int capture_count;
}

final class FpBoundingBox extends ffi.Struct {
  @ffi.Int32()
  external int min_x;

  @ffi.Int32()
  external int min_y;

  @ffi.Int32()
  external int max_x;

  @ffi.Int32()
  external int max_y;
}

final class FpProcessedFinger extends ffi.Struct {
  @ffi.Int32()
  external int finger_code;

  @ffi.Int32()
  external int quality_score;

  @ffi.Int32()
  external int minutia_count;

  @ffi.Int32()
  external int is_live;

  @ffi.Int32()
  external int resolution_ppi;

  @ffi.Double()
  external double scale_factor;

  external ffi.Pointer<ffi.Uint8> normalized_image;

  @ffi.Int32()
  external int normalized_image_size;

  external ffi.Pointer<ffi.Uint8> iso_template;

  @ffi.Int32()
  external int iso_template_size;

  external ffi.Pointer<FpMinutia> minutiae;

  @ffi.Int32()
  external int minutiae_count;

  external ffi.Pointer<ffi.Uint8> encrypted_data;

  @ffi.Int32()
  external int encrypted_data_size;
}

const int FP_FINGER_UNKNOWN = 0;

const int FP_FINGER_RIGHT_THUMB = 1;

const int FP_FINGER_RIGHT_INDEX = 2;

const int FP_FINGER_RIGHT_MIDDLE = 3;

const int FP_FINGER_RIGHT_RING = 4;

const int FP_FINGER_RIGHT_LITTLE = 5;

const int FP_FINGER_LEFT_THUMB = 6;

const int FP_FINGER_LEFT_INDEX = 7;

const int FP_FINGER_LEFT_MIDDLE = 8;

const int FP_FINGER_LEFT_RING = 9;

const int FP_FINGER_LEFT_LITTLE = 10;

const int FP_MINUTIA_BIFURCATION = 0;

const int FP_MINUTIA_RIDGE_ENDING = 1;

const int FP_LIVENESS_NOT_LIVE = 0;

const int FP_LIVENESS_LIVE = 1;

const int FP_LIVENESS_UNKNOWN = -1;

const int FP_STATE_IDLE = 0;

const int FP_STATE_LEFT_SLAP = 1;

const int FP_STATE_RIGHT_SLAP = 2;

const int FP_STATE_THUMBS = 3;

const int FP_STATE_PROCESSING = 4;

const int FP_STATE_COMPLETE = 5;

const int FP_EVENT_START = 0;

const int FP_EVENT_LEFT_SLAP_DONE = 1;

const int FP_EVENT_RIGHT_SLAP_DONE = 2;

const int FP_EVENT_THUMBS_DONE = 3;

const int FP_EVENT_RESET = 4;

const int FP_QUALITY_EXCELLENT = 1;

const int FP_QUALITY_GOOD = 2;

const int FP_QUALITY_FAIR = 3;

const int FP_QUALITY_POOR = 4;

const int FP_QUALITY_UNCLASSIFIABLE = 5;

const int FP_OK = 0;

const int FP_ERR_INVALID_INPUT = -1;

const int FP_ERR_PROCESSING_FAILED = -2;

const int FP_ERR_OUT_OF_MEMORY = -3;

const int FP_ERR_NOT_INITIALIZED = -4;

const int FP_ERR_BUFFER_TOO_SMALL = -5;

const int FP_ERR_LIVENESS_FAILED = -6;
